[versions]
agp = "8.13.2"
compose = "1.9.3"
kotlin = "2.3.0"
coroutines = "1.10.2"
voyager = "1.1.0-beta03"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
compose-multiplatorm = { id = "org.jetbrains.compose", version.ref = "compose" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
dokka = "org.jetbrains.dokka:2.1.0"
kotlin-atomicfu = { id = "org.jetbrains.kotlin.plugin.atomicfu", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ktlint = "org.jlleitschuh.gradle.ktlint:14.0.1"
maven-publish = "com.vanniktech.maven.publish:0.35.0"

[libraries]
android-activity-compose = "androidx.activity:activity-compose:1.12.2"
android-appcompat = "androidx.appcompat:appcompat:1.7.1"
android-webkit = "androidx.webkit:webkit:1.15.0"
compose-navigation = "org.jetbrains.androidx.navigation:navigation-compose:2.9.1"
material-icons-core = "org.jetbrains.compose.material:material-icons-core:1.7.3"
kcef = "dev.datlag:kcef:2025.03.23"
kermit = "co.touchlab:kermit:2.0.8"
kotlin-atomicfu = "org.jetbrains.kotlinx:atomicfu:0.29.0"
kotlin-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
kotlin-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlin-coroutines-swing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "coroutines" }
kotlin-serialization-json = "org.jetbrains.kotlinx:kotlinx-serialization-json:1.9.0"
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
voyager-navigator = { module = "cafe.adriel.voyager:voyager-navigator", version.ref = "voyager" }
voyager-tabNavigator = { module = "cafe.adriel.voyager:voyager-tab-navigator", version.ref = "voyager" }
